# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    build:
        description: "A very simple command for demonstration purposes"
        
        docker:
        
        - image: circleci/openjdk:11-browsers-legacy

        working_directory: ~/repo

        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m   
        
        steps:
        
        - run: mvn package
        
        - run: mvn -X verify
