orbs:
  maven: circleci/maven@x.y
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          command: '-X install'
  #maven_test:
    #jobs:
      - maven/test # checkout, build, test, and upload test results
